routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::resource('movies','MovieController')->only(['index','show']);
Route::get('/','welcomeController@index')->name('welcome');

Route::post('/movies/{movie}/increment_views','MovieController@increment_views')->name('movies.increment_views');
Route::post('/movies/{movie}/toggle_favorite','MovieController@toggle_favorite')->name('movies.toggle_favorite');

Route::get('/','welcomeController@index')->name('welcome');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google|twitter');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google|twitter');
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/dashboard/MovieController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use App\Category;
use App\Jobs\StreamMovie;
use App\Movie;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image;
use Intervention\Image\ImageManager;

class MovieController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_movies')->only(['index']);
        $this->middleware('permission:create_movies')->only(['create', 'store']);
        $this->middleware('permission:update_movies')->only(['edit', 'update']);
        $this->middleware('permission:delete_movies')->only(['destroy']);

    }// end of __construct

    public function index()
    {
        
        $categories = Category::all();
        $movies = Movie::whenSearch(request()->search)
            ->whenCategory(request()->category)
            ->with('categories')
            ->paginate(5);

        return view('dashboard.movies.index', compact('categories', 'movies'));

    }//end of index

    public function create()
    {
        $categories = category::all();
        $movie = Movie::create([]);

        return view('dashboard.movies.create', compact('categories' ,'movie'));

    }//end of create

    public function store(Request $request)
    {
        $movie = Movie::FindOrFail($request->movie_id);
        $movie->update([
            'name' => $request->name,
            'path' => $request->file('movie')->store('movies'),
        ]);

        //the job in background
        $this->dispatch(new StreamMovie($movie));

        return $movie;

    }//end of store

    public function show(Movie $movie)
    {
        return $movie;

    }// end of show

    public function edit(Movie $movie)
    {
        $categories = category::all();
    
        return view('dashboard.movies.edit', compact('movie','categories'));

    }//end of edit

    public function update(Request $request, Movie $movie)
    {
    if ($request->type == 'publish') {
        $request->validate([
            'name' => 'required|unique:movies,name,' . $movie->id,
            'description' => 'required',
            'poster' => 'required|image',
            'image' => 'required|image',
            'categories' => 'required|array',
            'year' => 'required',
            'rating' => 'required', 
        ]);

    
    }else {
        $request->validate([
            'name' => 'required|unique:movies,name,' . $movie->id,
            'description' => 'required',
            'poster' => 'nullable|sometimes|image',
            'image' => 'nullable|sometimes|image',
            'categories' => 'required|array',
            'year' => 'required',
            'rating' => 'required', 
        ]);
  
    }
    $request_data= $request->except(['poster','image']);
    if ($request->poster) {

        $this->remove_previous('poster',$movie);
        $poster = Image::make($request->poster)
        ->resize (255,378)
        ->encode('jpg',50);
        Storage::disk('local')->put('public/images/'.$request->poster->hashName(),(string)$poster,'public');
            
        $request_data['poster'] =  $request->poster->hashName();
    }


        if ($request->image) {
    $this->remove_previous('image',$movie);

            $image = Image::make($request->image)
            ->encode('jpg');
            Storage::disk('local')->put('public/images/'.$request->image->hashName(),(string)$image,'public');
       $request_data['image'] =  $request->image->hashName();
        }

    $movie->update($request_data);
    $movie->categories()->sync($request->categories); 
    session()->flash('success','Data Added Successfully');
    return redirect(route('dashboard.movies.index'));
    }//end of update


    public function destroy(Movie $movie)
    {
        Storage::disk('local')->deleteDirectory('public/movies'.$movie->id);
        Storage::disk('local')->delete($movie->path);

        Storage::disk('local')->delete('public/images'.$movie->poster);
        Storage::disk('local')->delete('public/images'.$movie->image);
        $movie->delete();
        session()->flash('success', 'Data deleted successfully');
        return redirect()->route('dashboard.movies.index');

    }//end of destroy

    private function remove_previous($image_type, $movie)
    {
            if ($image_type == 'poster') {
                if ($movie->poster != null) {
                    Storage::disk('local')->delete('public/images'.$movie->poster);

                }
            } #endif
            else {
                if ($movie->image != null) {
                    Storage::disk('local')->delete('public/images'.$movie->image);

                }
            } //end else

    }// end of remove_previous

 

}//end of controller

app/Http/Controllers/dashboard/categoryController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\category;
class categoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_categories')->only(['index']);
        $this->middleware('permission:create_categories')->only(['create', 'store']);
        $this->middleware('permission:update_categories')->only(['edit', 'update']);
        $this->middleware('permission:delete_categories')->only(['destroy']);

    }// end of __construct
    public function index(category $category )
    {
        $categories = Category::WhenSearch(request()->search)->withCount('movies')->paginate(2);
        return view('dashboard.categories.index', compact('categories'));
    }

     public function create()
    {
        return view('dashboard.categories.create');
    }

     public function store(Request $request , category $category)
    {
        request()->validate([
            'name'=>'required|string|min:4|max:30|unique:categories,name',
        ]);
        // dd($request->all());
        $category->create([
            'name'=>$request->name
        ]);
        session()->flash('success','Data Added Successfully');
        return redirect(route('dashboard.categories.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit(category $category)
    {
        return view('dashboard.categories.edit',compact('category'));
    }

   
    public function update(Request $request, category $category)
    {
        request()->validate([
            'name'=>'required|string|min:4|max:30|unique:categories,name,' .$category->id ,
        ]);
        $category->update([
            'name'=>$request->name
        ]);
        session()->flash('success','Data Updated Successfully');
        return redirect(route('dashboard.categories.index'));
    }

    public function destroy(category $category)
    {
        $category->delete();
        session()->flash('success','Data deleted Successfully');
        return redirect(route('dashboard.categories.index'));
    }
}

app/Http/Controllers/dashboard/roleController.php
<?php

namespace App\Http\Controllers\dashboard;
use App\role;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class roleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_roles')->only(['index']);
        $this->middleware('permission:create_roles')->only(['create', 'store']);
        $this->middleware('permission:update_roles')->only(['edit', 'update']);
        $this->middleware('permission:delete_roles')->only(['destroy']);

    }// end of __constr
    public function index(role $role )
    {
        $roles = role::WhereRoleNot(['super_admin'])->WhenSearch(request()->search)->with('permissions')->paginate(10);
        return view('dashboard.roles.index', compact('roles'));
    }

     public function create()
    {
        return view('dashboard.roles.create');
    }

     public function store(Request $request , role $role)
    {
        request()->validate([
            'name' => 'required|unique:roles,name,' . $role->id,
            'permissions'=>'required|array|min:1',
        ]);
        // dd($request->all());
        $role= role::create($request->all());
        $role->attachPermissions($request->permissions);
        session()->flash('success','Role ADDED Successfully');
        return redirect(route('dashboard.roles.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit(role $role)
    {
        return view('dashboard.roles.edit',compact('role'));
    }

   
    public function update(Request $request, role $role)
    {
        request()->validate([
            'name'=>'required|string|min:4|max:30|unique:roles,name,' . $role->id ,
            'permissions'=>'required|array|min:1',
       
            ]);
        $role->update($request->all());
        $role->syncPermissions($request->permissions);
        session()->flash('success','Data Updated Successfully');
        return redirect(route('dashboard.roles.index'));
    }

    public function destroy(role $role)
    {
        $role->delete();
        session()->flash('success','Data deleted Successfully');
        return redirect(route('dashboard.roles.index'));
    }
}

app/Http/Controllers/dashboard/settingsController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class settingsController extends Controller
{
    public function social_login(){
        return view('dashboard.settings.social_login');

    }

    public function social_links(){
        return view('dashboard.settings.social_links');
        
    }

    public function store(request $request){
        setting($request->all())->save();
        session()->flash('success','Data Added Successfully');
        return redirect()->back();
    }
}

app/Http/Controllers/dashboard/userController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\user;
use App\role;

class userController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_users')->only(['index']);
        $this->middleware('permission:create_users')->only(['create', 'store']);
        $this->middleware('permission:update_users')->only(['edit', 'update']);
        $this->middleware('permission:delete_users')->only(['destroy']);

    }// end of __construct
    public function index(user $user )
    {
        $roles = Role::whereRoleNot('super_admin')->get();


        $users = user::whereRoleNot('super_admin')
        ->WhenSearch(request()->search)
        ->whenRole(request()->role_id)
        ->with('roles')->paginate()->all();
        return view('dashboard.users.index', compact('roles','users'));
    }

     public function create()
    {
        $roles = role::WhereRoleNot(['super_admin','admin'])->get();
        return view('dashboard.users.create',compact('roles'));
    }

     public function store(Request $request , user $user)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,' ,
            'password' => 'required|confirmed|string|min:6|max:50',            
            'role_id'=>'required|numeric',
        ]);
      
        $request->merge(['password'=>bcrypt($request->password)]);
        // dd($request->all());
        $user= user::create($request->all());
        $user->attachRoles(['admin',$request->Role_id]);
        session()->flash('success','User ADDED Successfully');
        return redirect(route('dashboard.users.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit(user $user)
    {
        $roles= role::WhereRoleNot(['super_admin','admin'])->get();
        return view('dashboard.users.edit',compact('user','roles'));
    }

   
    public function update(Request $request, user $user)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,' . $user->id,
            'role_id'=>'required|numeric',
       
            ]);
        $user->update($request->all());
        $user->syncRoles(['admin',$request->role_id]);
        session()->flash('success','Data Updated Successfully');
        return redirect(route('dashboard.users.index'));
    }

    public function destroy(user $user)
    {
        $user->delete();
        session()->flash('success','Data deleted Successfully');
        return redirect(route('dashboard.users.index'));
    }
}//end of controller

app/Http/Controllers/dashboard/welcomeController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\movie;
use App\category;
use App\user;

class welcomeController extends Controller
{
        public function index(){
            $categories_count = category::count();
            $users_count = user::whereRole('user')->count();
            $movies_count = movie::where('percent', 100)->count();

            return view('dashboard.welcome',compact('categories_count','movies_count','users_count'));
        }//end func
}//end class

resources/views/dashboard/movies/create.blade.php
@extends('layouts.dashboard.app')

@push('styles')
    <style>
        #movie__upload-wrapper {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 25vh;
            flex-direction: column;
            cursor: pointer;
            border: 1px solid black;
        }
    </style>

@endpush

@section('content')

    <div>
        <h2>Movies</h2>
    </div>

    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.welcome') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('dashboard.movies.index') }}">Movie</a></li>
        <li class="breadcrumb-item active">Add</li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="tile mb-4">

                <div id="movie__upload-wrapper"
                     onclick="document.getElementById('movie__file-input').click()"
                     style="display: {{ $errors->any() ? 'none' : 'flex' }};"
                >
                    <i class="fa fa-video-camera fa-2x"></i>
                    <p>Click to upload</p>
                </div>

                <input type="file"
                       data-movie-id="{{ $movie->id }}"
                       data-url="{{ route('dashboard.movies.store') }}"
                       id="movie__file-input"
                       style="display: none;">

                <form id="movie__properties"
                      method="post"
                      action="{{ route('dashboard.movies.update', ['movie'=>$movie->id,'type'=>'publish']) }}"
                      enctype="multipart/form-data"
                      style="display: {{ $errors->any() ? 'block' : 'none' }};"
                >
                    @csrf
                    @method('put')

                    @include('dashboard.partials._errors')

                    {{--progress bar--}}
                    <div class="form-group" style="display: {{ $errors->any() ? 'none' : 'block' }};">
                        <label id="movie__upload-status">Uploading</label>
                        <div class="progress">
                            <div class="progress-bar" id="movie__upload-progress" role="progressbar"></div>
                        </div>
                    </div>

                    {{--name--}}
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" id="movie__name" value="{{ old('name', $movie->name) }}" class="form-control">
                    </div>

                    {{--description--}}
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" class="form-control">{{ old('description', $movie->description) }}</textarea>
                    </div>

                    {{--poster--}}
                    <div class="form-group">
                        <label>Poster</label>
                        <input type="file" name="poster" class="form-control">
                    </div>

                    {{--image--}}
                    <div class="form-group">
                        <label>Image</label>
                        <input type="file" name="image" class="form-control">
                    </div>

                    {{--categories--}}
                    <div class="form-group">
                        <label>Category</label>
                        <select name="categories[]" class="form-control select2" multiple>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}"
                                        {{$category->id}}
                                >
                                {{ in_array($category->id, $movie->categories->pluck('id')->toArray()) ? 'selected' : ''}}

                                </option>
                            @endforeach
                        </select>
                    </div>


                    {{--year--}}
                    <div class="form-group">
                        <label>Year</label>
                        <input type="text" name="year" value="{{ old('year', $movie->year) }}" class="form-control">
                    </div>

                    {{--rating--}}
                    <div class="form-group">
                        <label>Rating</label>
                        <input type="number" min="1" name="rating" value="{{ old('rating', $movie->rating) }}" class="form-control">
                    </div>

                    <div class="form-group">
                        <button type="submit" id="movie__submit-btn" style="display: {{ $errors->any() ? 'block' : 'none' }};" class="btn btn-primary"><i class="fa fa-plus"></i> Publish</button>
                    </div>

                </form><!-- end of form -->

            </div><!-- end of tile -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

resources/views/dashboard/movies/edit.blade.php
@extends('layouts.dashboard.app')

@section('content')

    <div>
        <h2>Movies</h2>
    </div>

    <ul class="breadcrumb mt-2">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.welcome') }}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{{ route('dashboard.movies.index') }}">Movies</a></li>
        <li class="breadcrumb-item active">Edit</li>
    </ul>

    <div class="row">
        <div class="col-md-12">
            <div class="tile shadow mb-4">

                <form id="movie__properties"
                      method="post"
                      action="{{ route('dashboard.movies.update', ['movie' => $movie->id, 'type' => 'update']) }}"
                      enctype="multipart/form-data"
                >
                    @csrf
                    @method('put')

                    @include('dashboard.partials._errors')

                    {{--name--}}
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" name="name" id="movie__name" value="{{ old('name', $movie->name) }}" class="form-control">
                    </div>

                    {{--description--}}
                    <div class="form-group">
                        <label>Description</label>
                        <textarea name="description" class="form-control">{{ old('description', $movie->description) }}</textarea>
                    </div>

                    {{--poster--}}
                    <div class="form-group">
                        <label>Poster</label>
                        <input type="file" name="poster" class="form-control">
                        <img src="{{ $movie->poster_path }}" style=" margin-top: 10px; width: 255px; height: 378px;" alt="">
                    </div>

                    {{--image--}}
                    <div class="form-group">
                        <label>Image</label>
                        <input type="file" name="image" class="form-control">
                        <img src="{{ $movie->image_path }}" style=" margin-top: 10px; width: 300px; height: 300;" alt="">
                    </div>

                    {{--categories--}}
                    <div class="form-group">
                        <label>Category</label>
                        <select name="categories[]" class="form-control select2" multiple>
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}"
                                        {{ in_array($category->id, $movie->categories->pluck('id')->toArray()) ? 'selected' : ''}}
                                >
                                    {{ $category->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    {{--year--}}
                    <div class="form-group">
                        <label>Year</label>
                        <input type="text" name="year" value="{{ old('year', $movie->year) }}" class="form-control">
                    </div>

                    {{--rating--}}
                    <div class="form-group">
                        <label>Rating</label>
                        <input type="number" min="1" name="rating" value="{{ old('rating', $movie->rating) }}" class="form-control">
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</button>
                    </div>

                </form><!-- end of form -->

            </div><!-- end of tile -->

        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection

resources/views/dashboard/movies/index.blade.php
@extends('layouts.dashboard.app')

@section('content')

    <div>
        <h2>Movies</h2>
    </div>

    <ul class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('dashboard.welcome') }}">Dashboard</a></li>
        <li class="breadcrumb-item active">Movie</li>
    </ul>

    <div class="row">

        <div class="col-md-12">
            <div class="tile mb-4">

                <div class="row">

                    <div class="col-12">

                        <form action="">
                            <div class="row">

                                <div class="col-md-4">
                                    <div class="form-group">
                                        <input type="text" name="search" autofocus class="form-control" placeholder="search ny name, description, rating, year" value="{{ request()->search }}">
                                    </div>
                                </div><!-- end of col -->

                                <div class="col-md-4">
                       
                                </div><!-- end of col -->

                                <div class="col-md-4">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> Search</button>
                                   
                                        <a href="{{ route('dashboard.movies.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add</a>
                             
                                       
              
                                </div>
                            </div><!-- end of row -->

                        </form><!-- end of form -->

                    </div><!-- end of col 12 -->

                </div><!-- end of row -->

                <div class="row">
                    <div class="col-md-12">
                        @if ($movies->count() > 0)
                            <table class="table table-hover">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Name</th>
                                    <th>Description</th>
                           
                                    <th>Year</th>
                                    <th>Rating</th>
                                    <th>Action</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach ($movies as $index=>$movie)
                                    <tr>
                                        <td>{{ $index+1 }}</td>
                                        <td>{{ $movie->name }}</td>
                                        <td>{{ Str::limit($movie->description, 50) }}</td>

                                        <td>{{ $movie->year }}</td>
                                        <td>{{ $movie->rating }}</td>
                                        <td>
                                            @if (auth()->user()->hasPermission('update_movies'))
                                                <a href="{{ route('dashboard.movies.edit', $movie->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            @else
                                                <a href="#" disabled class="btn btn-warning btn-sm"><i class="fa fa-edit"></i> Edit</a>
                                            @endif
                                            @if (auth()->user()->hasPermission('delete_movies'))
                                                <form method="post" action="{{ route('dashboard.movies.destroy', $movie->id) }}" style="display: inline-block;">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="submit" class="btn btn-danger btn-sm delete"><i class="fa fa-trash"></i> Delete</button>
                                                </form><!-- end of form -->
                                            @else
                                                <a href="#" disabled class="btn btn-danger btn-sm"><i class="fa fa-trash"></i>Delete</a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach

                                </tbody>
                            </table>

                            {{ $movies->appends(request()->query())->links() }}

                        @else
                            <h3 style="font-weight: 400;">Sorry no records found</h3>
                        @endif
                    </div>
                </div>
            </div><!-- end of tile -->
        </div><!-- end of col -->

    </div><!-- end of row -->

@endsection