routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::resource('movies','MovieController')->only(['index','show']);
Route::get('/','welcomeController@index')->name('welcome');

Route::post('/movies/{movie}/increment_views','MovieController@increment_views')->name('movies.increment_views');
Route::post('/movies/{movie}/toggle_favorite','MovieController@toggle_favorite')->name('movies.toggle_favorite');

Route::get('/','welcomeController@index')->name('welcome');
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider', 'facebook|google|twitter');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider', 'facebook|google|twitter');
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/dashboard/categoryController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\category;
class categoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:read_categories')->only(['index']);
        $this->middleware('permission:create_categories')->only(['create', 'store']);
        $this->middleware('permission:update_categories')->only(['edit', 'update']);
        $this->middleware('permission:delete_categories')->only(['destroy']);

    }// end of __construct
    public function index(category $category )
    {
        $categories = Category::WhenSearch(request()->search)->withCount('movies')->paginate(2);
        return view('dashboard.categories.index', compact('categories'));
    }

     public function create()
    {
        return view('dashboard.categories.create');
    }

     public function store(Request $request , category $category)
    {
        request()->validate([
            'name'=>'required|string|min:4|max:30|unique:categories,name',
        ]);
        // dd($request->all());
        $category->create([
            'name'=>$request->name
        ]);
        session()->flash('success','Data Added Successfully');
        return redirect(route('dashboard.categories.index'));
    }

    public function show($id)
    {
        //
    }

    public function edit(category $category)
    {
        return view('dashboard.categories.edit',compact('category'));
    }

   
    public function update(Request $request, category $category)
    {
        request()->validate([
            'name'=>'required|string|min:4|max:30|unique:categories,name,' .$category->id ,
        ]);
        $category->update([
            'name'=>$request->name
        ]);
        session()->flash('success','Data Updated Successfully');
        return redirect(route('dashboard.categories.index'));
    }

    public function destroy(category $category)
    {
        $category->delete();
        session()->flash('success','Data deleted Successfully');
        return redirect(route('dashboard.categories.index'));
    }
}

resources/views/layouts/_footer.blade.php
<footer id="footer" class="py-3 bg-primary text-center text-white">
    <p class="mb-0 text-capitalize">&copy; all copy right reserved for Netflixify 2020</p>
    <div class="social__icons">
        <a href="{{ setting('facebook_link') }}" class="text-white mr-2" target="_blank"><i class="fab fa-facebook fa-1x"></i></a>
        <a href="{{ setting('youtube_link') }}" class="text-white mr-2" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="{{ setting('youtube_link') }}" class="text-white mr-2" target="_blank"><i class="fab fa-youtube"></i></a>
    </div>
</footer>

resources/views/layouts/_nav.blade.php
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">

    <div class="container">

        <a class="navbar-brand" href="{{ route('welcome') }}">Netflix<span class="text-primary font-weight-bold">ify</span></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <form action="" class="col-12 col-md-6 p-0 mt-1">
                <div class="input-group">
                    <input type="search" class="form-control bg-transparent border-0" placeholder="Search for your favorite movies">
                    <div class="input-group-append">
                        <span class="input-group-text bg-transparent text-white border-0" id="basic-addon2"><i class="fas fa-search"></i></span>
                    </div>
                </div>
            </form><!-- end of form -->

            <ul class="navbar-nav ml-auto">
                @auth
                    <li class="nav-item mr-2">
                            <i class="fa fa-heart"></i>
                            <a href="{{route('movies.index',['favorite'=>1])}}" class="nav-link text-white" style="position: relative;">
                            <i class="fa fa-heart"></i>
                            <span class="bg-primary text-white d-flex justify-content-center align-items-center"
                                  style="position: absolute; top: 0; right: -15px; width: 30px; height: 20px; border-radius: 50px;"
                                  id="nav__fav-count"
                                  data-fav-count="{{ auth()->user()->movies_count }}"
                            >
                            {{ auth()->user()->movies_count > 9 ? '9+' : auth()->user()->movies_count }}
                            </span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ auth()->user()->name }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @if (auth()->user()->hasRole('super_admin') || auth()->user()->hasRole('admin'))
                                <a class="dropdown-item" href="{{ route('dashboard.welcome') }}">
                                    <i class="fa fa-tachometer-alt"></i>
                                    Dashboard
                                </a>
                            @endif
                            <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out-alt"></i>
                                Logout
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </a>
                        </div>
                    </li>

                @else
                    <a href="{{ route('login') }}" class="btn btn-primary mb-2 mb-md-0 mr-0 mr-md-2">Login</a>
                    <a href="{{ route('register') }}" class="btn btn-outline-light">Register</a>
                @endauth
            </ul>

        </div><!-- end of collapse -->

    </div><!-- end of container fluid-->

</nav><!-- end of nav -->

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Netflixify</title>

    <!--font awesome-->
    <script src="https://kit.fontawesome.com/bcd3dd02f3.js" crossorigin="anonymous"></script>
    

    <!--bootstrap-->
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">

    <!--vendor css-->
    <link rel="stylesheet" href="{{ asset('css/vendor.min.css') }}">

    <!--google font-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,500,700&display=swap" rel="stylesheet">

    <!--main styles -->
    <link rel="stylesheet" href="{{ asset('css/main.min.css') }}">

    {{--easy auto complete--}}
    <link rel="stylesheet" href="{{ asset('plugins/easyautocomplete/easy-autocomplete.min.css') }}">
    <style>
        .fw-900 {
            font-weight: 900;
        }

        .easy-autocomplete {
            width: 50%;
        }

        .easy-autocomplete input {
            color: white !important;
        }

        .eac-icon-left .eac-item img {
            max-height: 5f0px !important;
        }
    </style>
</head>
<body>

@yield('content')

<!--jquery-->
<script src="{{ asset('js/jquery-3.4.0.min.js') }}"></script>

<!--bootstrap-->
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/popper.min.js') }}"></script>

<!--vendor js-->
<script src="{{ asset('js/vendor.min.js') }}"></script>

<!--main scripts-->
<script src="{{ asset('js/main.min.js') }}"></script>

{{--player js--}}
<script src="{{ asset('js/playerjs.js') }}"></script>

{{--easy auto compelete--}}
<script src="{{ asset('plugins/easyautocomplete/jquery.easy-autocomplete.min.js') }}"></script>

{{--custom movies--}}
<script src="{{ asset('js/custom/movie.js') }}"></script>

<script>

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    var options = {
        url: function (search) {
            return "/movies?search=" + search;
        },

        getValue: "name",

        template: {
            type: 'iconLeft',
            fields: {
                iconSrc: "poster_path"
            }
        },

        list: {
            onChooseEvent: function () {
                var movie = $('.form-control[type="search"]').getSelectedItemData();
                var url = window.location.origin + '/movies/' + movie.id;
                window.location.replace(url);
            }
        }
    };

    $('.form-control[type="search"]').easyAutocomplete(options)

    $(document).ready(function () {

        $("#banner .movies").owlCarousel({
            loop: true,
            nav: false,
            items: 1,
            dots: false,
        });

        $(".listing .movies").owlCarousel({
            loop: true,
            nav: false,
            stagePadding: 50,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 4
                }
            },
            dots: false,
            margin: 15,
            loop: true,
        });

    });
</script>

@stack('scripts')

</body>
</html>